# Generated by Django 3.1.3 on 2020-11-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=36)),
                ('dateCreated', models.DateField(auto_now=True)),
                ('professor', models.CharField(default='', max_length=36)),
                ('className', models.CharField(default='', max_length=36)),
                ('section', models.IntegerField()),
                ('weekNumber', models.IntegerField()),
            ],
        ),
    ]
