# Generated by Django 3.1.3 on 2020-11-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='weekNumber',
        ),
        migrations.AlterField(
            model_name='course',
            name='className',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
